name: 'Validate Kubernetes Manifests'
description: 'Validate Kubernetes manifests using Kubeconform'
inputs:
  envs:
    description: 'Comma-separated list (e.g. `prod,qa`) of kustomize overlays (env names) to validate. The action can detect and dynamically validate all overlays when this variable is set to `auto`'
    required: true
    default: 'auto'
  service:
    description: 'The folder name of the service you want to validate. If given a comma separated list, will iterate over all'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.envs }}
    - ${{ inputs.service }}
